name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [main]  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      #- name: Create .env
      #  run: echo 'PORT=${{secrets.PORT }}' > .env
        
      - name: Docker build
        run: docker build -t flachens/flask-app .
      - name: Docker run
        run: docker run -d -p 5000:80 flachens/flask-app

      